// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayStats.Data;

namespace PlayStats.Migrations
{
    [DbContext(typeof(CollectionContext))]
    [Migration("20190315061806_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("PlayStats.Data.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DesireToPlay");

                    b.Property<bool>("IsDelivered");

                    b.Property<bool>("IsGenuine");

                    b.Property<string>("Name");

                    b.Property<int>("ObjectId");

                    b.Property<Guid>("ParentId");

                    b.Property<double>("PurchasePrice");

                    b.Property<int>("Rating");

                    b.Property<double>("SellPrice");

                    b.Property<bool>("WantToSell");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("PlayStats.Data.Play", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<TimeSpan>("Duration");

                    b.Property<Guid>("GameId");

                    b.Property<int>("PlayerCount");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("PlayStats.Data.Game", b =>
                {
                    b.HasOne("PlayStats.Data.Game", "Parent")
                        .WithMany("LinkedGames")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PlayStats.Data.Play", b =>
                {
                    b.HasOne("PlayStats.Data.Game", "Game")
                        .WithMany("Plays")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
